export const FETCHING_RATES = 'FETCHING_RATES';

export const FETCHING_RATES_FINISHED = 'FETCHING_RATES_FINISHED';

export const UPDATE_CURRENCIES = 'UPDATE_CURRENCIES';

export const UPDATE_CURRENCY_PAIR = 'UPDATE_CURRENCY_PAIR';

export const UPDATE_FROM_CURRENCY = 'UPDATE_FROM_CURRENCY';

export const UPDATE_FROM_CURRENCY_AMOUNT = 'UPDATE_FROM_CURRENCY_AMOUNT';

export const UPDATE_RATES = 'UPDATE_RATES';

export const UPDATE_TO_CURRENCY = 'UPDATE_TO_CURRENCY';

export const UPDATE_TO_CURRENCY_AMOUNT = 'UPDATE_TO_CURRENCY_AMOUNT';

export const UPDATE_USER_BALANCE = 'UPDATE_USER_BALANCE';

export default {
  FETCHING_RATES,
  FETCHING_RATES_FINISHED,
  UPDATE_CURRENCIES,
  UPDATE_CURRENCY_PAIR,
  UPDATE_FROM_CURRENCY,
  UPDATE_FROM_CURRENCY_AMOUNT,
  UPDATE_RATES,
  UPDATE_TO_CURRENCY,
  UPDATE_TO_CURRENCY_AMOUNT,
  UPDATE_USER_BALANCE
};
